language: ruby
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
    - COMMIT_AUTHOR_EMAIL="travis-ci@metanorma.com"
addons:
  apt:
    packages:
      - unzip
rvm:
  - 2.5.3
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash" ; nvm use mn-node ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb ; fi
script:
  - make clean all publish
deploy:
  skip_cleanup: true
  provider: script
  script: bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/deploy-to-gh-pages.sh | bash"
  on:
    branch: master
