language: ruby
dist: xenial
# branches:
#   only:
#     - master
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
    - COMMIT_AUTHOR_EMAIL="travis-ci@metanorma.com"
    - ENCRYPTION_LABEL="76cf0ca8b1d3"
rvm:
  - 2.5.3
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
script:
  - make clean all publish
deploy:
  skip_cleanup: true
  provider: script
  script: bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/deploy-to-gh-pages.sh | bash"
  on:
    branch: master
