include Makefile.win.main

#
# OVERRIDEN TARGETS
#

all: sources/controls/xx-all.adoc documents.html
	$(MAKE) -f Makefile.win.main $@

clean:
	$(MAKE) -f Makefile.main $@
	del /q controls caiq.yaml

%.adoc: sources/controls/%.adoc

#
# CUSTOM TARGETS
#

sources/controls:
	mkdir -p $@;

caiq.yaml: bundle
	bundle exec csa-ccm ccm-yaml 3.0.1 -o $@

sources/controls/%.adoc: sources/controls caiq.yaml
	scripts/build.rb
