= CSA Cloud Controls Matrix 3.0.1 Consensus Assessment Questionnaire in Metanorma

image:https://travis-ci.com/metanorma/csa-caiq.svg?branch=master["Build Status", link="https://travis-ci.com/metanorma/csa-caiq"]

This document is used to allow automatic generation of a filled CSA
CAIQ 3.0.1 using the machine-readable requirements functionality in
Metanorma.

This document is available in its rendered forms here:

* https://metanorma.github.io/csa-caiq/[CSA Cloud Controls Matrix 3.0.1 Consensus Assessment Questionnaire (HTML)]
* https://metanorma.github.io/csa-caiq/document.pdf[PDF]
* https://metanorma.github.io/csa-caiq/document.xml[Metanorma XML]
//* https://metanorma.github.io/csa-caiq/document.rxl[Relaton XML (Bibliographic item)]


Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://gitlab.com/metanorma/csa-caiq/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSAND XML (https://github.com/metanorma/metanorma-model-csand) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
//* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open document.html
----
