
.Audit Assurance & Compliance
[requirement,type="class",label="AAC",id="/ccm/3.0.1/aac",obligation="requirement"]
====

Audit Assurance & Compliance

.Audit Planning
[requirement,type="general",label="AAC-01",id="/ccm/3.0.1/aac/01"]
======
Audit plans shall be developed and maintained to address business process disruptions. Auditing plans shall focus on reviewing the effectiveness of the implementation of security operations. All audit activities must be agreed upon prior to executing any audits.

[verification,type="general",label="AAC-01.1",id="/ccm/3.0.1/aac/01/questions/1"]
========
Do you produce audit assertions using a structured, industry accepted format (e.g., CloudAudit/A6 URI Ontology, CloudTrust, SCAP/CYBEX, GRC XML, ISACA's Cloud Computing Management Audit/Assurance Program, etc.)?
========
======


.Independent Audits
[requirement,type="general",label="AAC-02",id="/ccm/3.0.1/aac/02"]
======
Independent reviews and assessments shall be performed at least annually to ensure that the organization addresses nonconformities of established policies, standards, procedures, and compliance obligations.

[verification,type="general",label="AAC-02.1",id="/ccm/3.0.1/aac/02/questions/1"]
========
Do you allow tenants to view your SOC2/ISO 27001 or similar third-party audit or certification reports?
========

[verification,type="general",label="AAC-02.2",id="/ccm/3.0.1/aac/02/questions/2"]
========
Do you conduct network penetration tests of your cloud service infrastructure regularly as prescribed by industry best practices and guidance?
========


[verification,type="general",label="AAC-02.3",id="/ccm/3.0.1/aac/02/questions/3"]
========
Do you conduct application penetration tests of your cloud infrastructure regularly as prescribed by industry best practices and guidance?
========

[verification,type="general",label="AAC-02.4",id="/ccm/3.0.1/aac/02/questions/4"]
========
Do you conduct internal audits regularly as prescribed by industry best practices and guidance?
========

[verification,type="general",label="AAC-02.5",id="/ccm/3.0.1/aac/02/questions/5"]
========
Do you conduct external audits regularly as prescribed by industry best practices and guidance?
========

[verification,type="general",label="AAC-02.6",id="/ccm/3.0.1/aac/02/questions/6"]
========
Are the results of the penetration tests available to tenants at their request?
========

[verification,type="general",label="AAC-02.7",id="/ccm/3.0.1/aac/02/questions/7"]
========
Are the results of internal and external audits available to tenants at their request?
========

[verification,type="general",label="AAC-02.8",id="/ccm/3.0.1/aac/02/questions/8"]
========
Do you have an internal audit program that allows for cross-functional audit of assessments?
========

======


.Information System Regulatory Mapping
[requirement,type="general",label="AAC-03",id="/ccm/3.0.1/aac/03"]
======
Organizations shall create and maintain a control framework which captures standards, regulatory, legal, and statutory requirements relevant for their business needs. The control framework shall be reviewed at least annually to ensure changes that could affect the business processes are reflected.

[verification,type="general",label="AAC-03.1",id="/ccm/3.0.1/aac/03/questions/1"]
========
Do you have the ability to logically segment or encrypt customer data such that data may be produced for a single tenant only, without inadvertently accessing another tenant's data?
========

[verification,type="general",label="AAC-03.2",id="/ccm/3.0.1/aac/03/questions/2"]
========
Do you have the capability to recover data for a specific customer in the case of a failure or data loss?
========

[verification,type="general",label="AAC-03.3",id="/ccm/3.0.1/aac/03/questions/3"]
========
Do you have the capability to restrict the storage of customer data to specific countries or geographic locations?
========

[verification,type="general",label="AAC-03.4",id="/ccm/3.0.1/aac/03/questions/4"]
========
Do you have a program in place that includes the ability to monitor changes to the regulatory requirements in relevant jurisdictions, adjust your security program for changes to legal requirements, and ensure compliance with relevant regulatory requirements?
========

======


====
