
.Application & Interface Security
[requirement,type="class",label="AIS",id="/ccm/3.0.1/ais",obligation="requirement"]
====

//Application & Interface Security


.Application Security
[requirement,type="general",label="AIS-01",id="/ccm/3.0.1/ais/01"]
======
Applications and programming interfaces (APIs) shall be designed, developed, deployed, and tested in accordance with leading industry standards (e.g., OWASP for web applications) and adhere to applicable legal, statutory, or regulatory compliance obligations.

[verification,type="general",label="AIS-01.1",id="/ccm/3.0.1/ais/01/questions/1"]
========
Do you use industry standards (Build Security in Maturity Model [BSIMM] benchmarks, Open Group ACS Trusted Technology Provider Framework, NIST, etc.) to build in security for your Systems/Software Development Lifecycle (SDLC)?
========

[verification,type="general",label="AIS-01.2",id="/ccm/3.0.1/ais/01/questions/2"]
========
Do you use an automated source code analysis tool to detect security defects in code prior to production?
========

[verification,type="general",label="AIS-01.3",id="/ccm/3.0.1/ais/01/questions/3"]
========
Do you use manual source-code analysis to detect security defects in code prior to production?
========

[verification,type="general",label="AIS-01.4",id="/ccm/3.0.1/ais/01/questions/4"]
========
Do you verify that all of your software suppliers adhere to industry standards for Systems/Software Development Lifecycle (SDLC) security?
========

[verification,type="general",label="AIS-01.5",id="/ccm/3.0.1/ais/01/questions/5"]
========
(SaaS only) Do you review your applications for security vulnerabilities and address any issues prior to deployment to production?
========

======


.Customer Access Requirements
[requirement,type="general",label="AIS-02",id="/ccm/3.0.1/ais/02"]
======
Prior to granting customers access to data, assets, and information systems, identified security, contractual, and regulatory requirements for customer access shall be addressed.

[verification,type="general",label="AIS-02.1",id="/ccm/3.0.1/ais/02/questions/1"]
========
Are all identified security, contractual, and regulatory requirements for customer access contractually addressed and remediated prior to granting customers access to data, assets, and information systems?
========

[verification,type="general",label="AIS-02.2",id="/ccm/3.0.1/ais/02/questions/2"]
========
Are all requirements and trust levels for customers’ access defined and documented?
========

======


.Data Integrity
[requirement,type="general",label="AIS-03",id="/ccm/3.0.1/ais/03"]
======
Data input and output integrity routines (i.e., reconciliation and edit checks) shall be implemented for application interfaces and databases to prevent manual or systematic processing errors, corruption of data, or misuse.

[verification,type="general",label="AIS-03.1",id="/ccm/3.0.1/ais/03/questions/1"]
========
Are data input and output integrity routines (i.e., reconciliation and edit checks) implemented for application interfaces and databases to prevent manual or systematic processing errors or corruption of data?
========

======


.Interface Security
[requirement,type="general",label="AIS-04",id="/ccm/3.0.1/ais/04"]
======
Policies and procedures shall be established and maintained in support of data security to include (confidentiality, integrity, and availability) across multiple system interfaces, jurisdictions, and business functions to prevent improper disclosure, alternation, or destruction.

[verification,type="general",label="AIS-04.1",id="/ccm/3.0.1/ais/04/questions/1"]
========
Is your Data Security Architecture designed using an industry standard (e.g., CDSA, MULITSAFE, CSA Trusted Cloud Architectural Standard, FedRAMP, CAESARS)?
========

======

====
